nia/routes.py
from flask import render_template, url_for, session, flash, redirect, request, jsonify, Blueprint
from nia import db, login_manager
from nia.forms import  SignupForm, LoginForm, NewdeviceForm
from flask_login import login_user, current_user, logout_user, login_required
from nia.models import User, Device, Telemetry, Methods
import secrets, random
from werkzeug.urls import url_parse

views = Blueprint('views',__name__)

@views.route('/')
@views.route('/index',methods=["GET"])
def index():
    return render_template('index.html')

@views.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.index'))
    form=LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        password=form.password.data
        if user is None  or password!=user.password:
            flash('wrong email/password','danger')
            return redirect(url_for('views.login'))
        login_user(user,remember=form.remember.data)
        next_page=request.args.get('next')
        if next_page:
            #page requiring authentication to gain access,once user logs in, 
            #they are redirected back to that page
            next_page=next_page.split('/')[-2:]
            next_page=next_page[0]+"."+next_page[1]
        if not next_page or url_parse(next_page).netloc!='':
            next_page='views.index'
        flash(f'Login successful','success')
        return redirect(url_for(next_page))
    return render_template('login.html', form=form)


@views.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('views.index'))
    form = SignupForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data, password= form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User account has been created successfully','success')
        usr=User.query.filter_by(email=form.email.data).first()
        login_user(usr)
        return redirect(url_for('views.index'))
    return render_template('register.html', form=form)

@views.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.index'))

@views.route('/account')
@login_required
def account():
    if current_user.is_authenticated:
        return render_template('index.html', username=current_user.username)
    else:
        flash('User Authentication required','danger')
        return redirect(url_for('views.login'))

@views.route('/adddevice', methods=['GET','POST'])
@login_required
def adddevice():
    if current_user.is_authenticated:
        groups = Methods.query.all()
        group_list=[(i.devicemethod, i.methodname) for i in groups]
        form = NewdeviceForm()
        form.devicemethod.choices=group_list
        device_key = generate_api_key()
        if form.validate_on_submit():
            device_data = Device(device_name=form.devicename.data, device_IP=form.deciveIP.data, device_method=form.devicemethod.data, api_key=device_key)
            db.session.add(device_data)
            db.session.commit()
            flash('Devive Channel Creation Successful', 'Success')
            return device_key
        return render_template('devices.html')
    else:
        flash('User Authentication required','danger')
        return redirect(url_for('views.login'))

def generate_api_key():
    aphrases=['Alpha','Bravo','Charlie','Delta','Echo','Foxtrot','Golf','Hotel','India','Juliet','Kilo','Lima','Mike','November','Oscar','Papa','Quebec','Romeo','Sierra','Tango','Uniform','Victor','Whiskey','X-ray','Yankee','Zulu']
    alist=[]
    token = secrets.token_hex(24)
    alist.append(token)
    tag = random.choice(aphrases)+secrets.token_hex(4)
    alist.append(tag)
    sep = '/'
    key = sep.join(alist)
    return key

nia/templates/account.html
{% extends 'layout.html' %}

{% block main_content %}
    <h1>User Account</h1>
{% endblock main_content %}

nia/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <script src="{{url_for('static', filename='style.js')}}"></script>


    {% if title %}
        <title>Nia IoT - {{ title }}</title>
    {% else %}
        <title>Nia IoT</title>
    {% endif %}
    
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark" style="background-image: linear-gradient(15deg, #ffc04a 10%, #ff6343 90%);">
            <div class="container">
                <div class="nav navbar-nav navbar-left" >
                    <a class="navbar-brand" style="color: #3A3A3A; font-size: 24px; font-weight: bold;" href="{{ url_for('views.index')}}">Nia IoT</a>
                    <a href="{{ url_for('views.index')}}" style="color: #3A3A3A;">Home</a>
                    <a href="#" style="color: #3A3A3A;">Telemetry</a>
                </div>
                <div class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <a href="{{ url_for('views.account')}}" style="color: #3A3A3A;">Account</a>
                    <a href="{{ url_for('views.logout')}}" style="color: #3A3A3A;">Sign out</a>
                    {% else %}
                    <a href="{{ url_for('views.login')}}" style="color: #3A3A3A;">Sign In</a>
                    <a href="{{ url_for('views.register')}}" style="color: #3A3A3A;">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>
    <main class="container">
	{% block notifications%}
		{% with messages = get_flashed_messages(with_categories=true) %}
  <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
 	 	 {% if messages %}
   		  {% for category, message in messages %}
     		   <div class="alert alert-{{ category }} alert-dismissible" role="alert">
      		   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
     		  <!-- <strong>Title</strong> --> {{ message }}
     		  </div>
   		  {% endfor %}
  		 {% endif %}
		{% endwith %}  
	{%endblock%}
        {% block main_content %} {% endblock main_content %}
    </main>
    <footer>

    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

nia/templates/devices.html
{% extends 'layout.html' %}

{% block main_content %}
    <h1>User Account</h1>
{% endblock main_content %}

nia/templates/index.html
{% extends 'base.html' %}

{% block main_content %}
    <h1>Welcome to Nia IoT Platform </h1>

    <canvas id="mychart" width="600" height="400"></canvas>
{% endblock main_content %}

nia/templates/layout.html
{% extends 'bootstrap/base.html' %}


{% block title %} Nia IoT {% endblock title %}


{% block navbar %}
    <nav class="navbar navbar-dark bg-dark" style="background-image: linear-gradient(15deg, #ffc04a 10%, #ff6343 90%);">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only" >Toggle navigation</span>
                    <span class="icon-bar" style="background-color: #3A3A3A;"></span>
                    <span class="icon-bar" style="background-color: #3A3A3A;" ></span>
                    <span class="icon-bar" style="background-color: #3A3A3A;" ></span>
                </button>
                <a class="navbar-brand" style="color: #3A3A3A; font-size: 18px; font-weight: bold;" href="{{ url_for('views.index')}}">Nia IoT</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav" >
                    <li><a href="{{ url_for('views.index')}}" style="color: #3A3A3A;">Home</a></li>
                    <li><a href="#" style="color: #3A3A3A;">Telemetry</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('views.account')}}" style="color: #3A3A3A;">Account</a></li>
                    <li><a href="{{ url_for('views.logout')}}" style="color: #3A3A3A;">Sign out</a></li>
                    <li><a href="{{ url_for('views.login')}}" style="color: #3A3A3A;">Sign In</a></li>
                    <li><a href="{{ url_for('views.register')}}" style="color: #3A3A3A;">Sign Up</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock navbar %}
{% block content %}
    <div class="sidebar">
        <div>
            <img alt="Profile Pic">
            <h1>Header</h1>
        </div>
        <li>Mys devices</li>
    </div>
    <div class="container">
        {% block main_content %} {% endblock main_content %}
    </div>
{% endblock content %}

nia/templates/login.html
{% extends 'base.html' %}

{% block main_content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('views.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock main_content %}

nia/templates/register.html
{% extends 'base.html' %}

{% block main_content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign Up</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Hava An Account? <a class="ml-2" href="{{ url_for('views.login') }}">Sign In</a>
        </small>
    </div>
{% endblock main_content %}